# -*- coding: utf-8 -*-
"""[2025-2 해커톤]유저 더미데이터 생성.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gALHwjMSMHzctHP1gbNLsc4NsuNWlyY4
"""

import json
import random
import itertools

# -----------------------------------------------------------
# 1. 설정: 학과 리스트 및 상수
# -----------------------------------------------------------
MAJORS = [
    "국어국문학과", "국제학부", "역사학과", "교육학과", "글로벌인재학부",
    "행정학과", "미디어커뮤니케이션학과", "법학과",
    "경영학부", "경제학과",
    "호텔관광외식경영학부", "호텔외식관광프랜차이즈경영학과", "글로벌조리학과", "호텔외식비즈니스학과",
    "수학통계학과", "물리천문학과", "화학과",
    "생명시스템학부", "스마트생명산업융합학과",
    "AI융합전자공학과", "반도체시스템공학과", "컴퓨터공학과", "정보보호학과", "양자지능정보학과", "창의소프트학부", "지능IoT학과",
    "사이버국방학과", "국방AI로봇융합공학과", "인공지능데이터사이언스학과", "AI로봇학과", "지능정보융합학과", "콘텐츠소프트웨어학과",
    "건축공학과", "건축학과", "건설환경공학과", "환경융합공학과", "지구자원시스템공학과", "기계공학과",
    "우주항공시스템공학부", "나노신소재공학과", "양자원자력공학과", "국방시스템공학과",
    "회화과", "패션디자인학과", "음악과", "체육학과", "무용과", "영화예술학과",
    "자유전공학부", "인문사회계열", "경상호텔관광계열", "자연생명계열", "IT계열", "첨단융합계열", "공과계열"
]

TOTAL_USERS = 1000  # 생성할 총 인원 수

# -----------------------------------------------------------
# 2. 기능 함수: 16가지 유형(MBTI식) 생활 패턴 생성기
# -----------------------------------------------------------
def generate_lifestyle_profile():
    """
    16가지 유형 중 하나를 랜덤으로 골라, 약간의 노이즈를 섞은 생활 패턴 딕셔너리를 반환
    """
    # 4가지 축: [Time, Hygiene, Sensitivity, Social] (0 or 1)
    # 유형 랜덤 선택 (균등 분포)
    t_axis = random.choice([0, 1]) # 0: Morning, 1: Night
    h_axis = random.choice([0, 1]) # 0: Clean, 1: Dirty
    s_axis = random.choice([0, 1]) # 0: Sensitive, 1: Tough(무던)
    o_axis = random.choice([0, 1]) # 0: Introvert, 1: Extrovert

    noise = 0.1 # 10% 확률로 예외 행동

    profile = {}

    # (1) Time Axis (Morning=0 vs Night=1)
    base = t_axis
    profile['sleep_habit'] = base if random.random() > noise else 1-base
    profile['wake_up'] = 0 if t_axis == 1 else 1 # Night(1)이면 오전없음(0)
    if random.random() < noise: profile['wake_up'] = 1 - profile['wake_up']
    profile['activity_time'] = base if random.random() > noise else 1-base

    # (2) Hygiene Axis (Clean=0 vs Dirty=1)
    # 질문 로직: clean_immediate(1=바로, 0=나중), desk_status(1=정리, 0=더러움)
    # Dirty(1)이면 -> 0(나중/더러움)이 나와야 함. Clean(0)이면 -> 1
    h_val = 0 if h_axis == 1 else 1
    profile['clean_immediate'] = h_val if random.random() > noise else 1-h_val
    profile['desk_status'] = h_val if random.random() > noise else 1-h_val

    # clean_cycle: Dirty(1) -> 2 or 3 / Clean(0) -> 0 or 1
    if h_axis == 1:
        profile['clean_cycle'] = random.choice([2, 3])
    else:
        profile['clean_cycle'] = random.choice([0, 1])

    # (3) Sensitivity Axis (Sensitive=0? No, 질문상 1=예민, 0=무던)
    # Sensitive(0) -> 실제값 1 / Tough(1) -> 실제값 0
    s_val = 1 if s_axis == 0 else 0

    sens_cols = ['out_return', 'other_seat_tol', 'phone_noise',
                 'light_sensitivity', 'key_mouse_noise', 'space_privacy']
    for col in sens_cols:
        profile['out_return'] = s_val if random.random() > noise else 1-s_val
        profile[col] = s_val if random.random() > noise else 1-s_val

    # 알람: 예민(1)하면 바로 끔(1) / 둔하면 못들음(0)
    profile['alarm_habit'] = s_val if random.random() > noise else 1-s_val

    # (4) Social Axis (Introvert=0 vs Extrovert=1)
    # 질문: 1=친목/초대OK, 0=거리두기/싫음
    o_val = 1 if o_axis == 1 else 0
    profile['social_willingness'] = o_val if random.random() > noise else 1-o_val
    profile['friend_invite'] = o_val if random.random() > noise else 1-o_val

    # 기숙사 체류: Intro(0) -> 1(많이있음) / Extro(1) -> 0(잠만)
    d_val = 1 if o_axis == 0 else 0
    profile['dorm_stay'] = d_val if random.random() > noise else 1-d_val

    return profile

# -----------------------------------------------------------
# 3. 메인 데이터 생성 로직
# -----------------------------------------------------------
def create_mock_users(TOTAL_USERS):
    users = []
    generated_ids = set()

    # 학번 가중치 설정 (26학번이 가장 많고, 20학번으로 갈수록 줄어듦)
    # Years: 26, 25, 24, 23, 22, 21, 20
    years = [26, 25, 24, 23, 22, 21, 20]
    weights = [30, 25, 15, 12, 8, 6, 4] # 합 100이 되도록 대략 설정

    for _ in range(TOTAL_USERS):
        user = {}

        # 1. 학번 생성 (Unique 보장)
        while True:
            year = random.choices(years, weights=weights, k=1)[0]
            rand_suffix = random.randint(0, 1999) # 2000 이하 랜덤
            student_id = f"{year}01{rand_suffix:04d}"

            if student_id not in generated_ids:
                generated_ids.add(student_id)
                break

        user['student_id'] = student_id

        # 2. 나이 계산 (평균보다 1살 높게)
        # 26학번(1학년) -> 보통 20살. +1살 보정 = 21살 기준.
        # 기준 나이 = (27 - year) + 20
        base_age = (26 - year) + 21

        # 약간의 변동 (빠른년생 or N수) : -1 ~ +2
        age_variation = random.choice([-1, 0, 0, 1, 1, 2])
        final_age = base_age + age_variation

        # 범위 제한 (20 ~ 27)
        if final_age < 20: final_age = 20
        if final_age > 27: final_age = 27
        user['age'] = final_age

        # 3. 기본 정보
        user['gender'] = random.choice(['남성', '여성'])
        user['major'] = random.choice(MAJORS)

        # 4. 추가 호불호 정보 (O/X -> Boolean)
        user['is_smoker'] = random.choice([True, False])
        user['wants_smoker'] = random.choice([True, False]) # 흡연 룸메 가능?
        user['is_drinker'] = random.choice([True, False])
        user['wants_drinker'] = random.choice([True, False]) # 음주 룸메 가능?
        user['sensitive_heat'] = random.choice([True, False]) # 더위
        user['sensitive_cold'] = random.choice([True, False]) # 추위

        # 5. 생활 패턴 (16 Q&A) 병합
        lifestyle = generate_lifestyle_profile()
        user.update(lifestyle) # user 딕셔너리에 합치기

        users.append(user)

    return users

# -----------------------------------------------------------
# 4. 실행 및 JSON 저장
# -----------------------------------------------------------
mock_data = create_mock_users(TOTAL_USERS)

# 파일로 저장
file_path = 'dormitory_users.json'
with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(mock_data, f, ensure_ascii=False, indent=4)

print(f"✅ 총 {len(mock_data)}명의 데이터를 생성하여 '{file_path}'로 저장했습니다.")

# 미리보기 (상위 1명)
print("\n[데이터 미리보기 (1명)]")
print(json.dumps(mock_data[0], ensure_ascii=False, indent=4))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# 한글 폰트 설정 (Mac: 'AppleGothic', Win: 'Malgun Gothic')
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

def visualize_data_quality(df):
    # 'type_label'은 분석에서 제외하고 정답지로 따로 뺌
    X = df.drop(columns=['type_label'])
    y = df['type_label']

    # -------------------------------------------------------
    # 1. 히트맵 (Heatmap): 유형별 특징이 뚜렷한가?
    # -------------------------------------------------------
    # 유형별 평균값 계산
    type_means = df.groupby('type_label').mean()

    # 시각화
    plt.figure(figsize=(14, 10))
    sns.heatmap(type_means, cmap='RdBu_r', annot=False, linewidths=.5)
    plt.title('16개 유형별 설문 응답 패턴 (파란색=낮음/0, 빨간색=높음/1)', fontsize=15)
    plt.xlabel('설문 문항', fontsize=12)
    plt.ylabel('유형 (Type)', fontsize=12)
    plt.show()

    print("\n--- [히트맵 해석 팁] ---")
    print("1. 가로줄(유형)마다 색깔 패턴이 뚜렷하게 달라야 합니다.")
    print("2. 예를 들어 'M...(아침형)'으로 시작하는 유형들은 sleep_habit(수면시간)이 파란색(0)이어야 합니다.")
    print("3. 색깔이 뒤죽박죽 섞여있지 않고, 블록 형태(체크무늬)가 보이면 성공입니다.")

    # -------------------------------------------------------
    # 2. PCA 산점도 (Scatter Plot): 데이터가 잘 분리되는가?
    # -------------------------------------------------------
    # 데이터 정규화 (스케일링)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # 2차원으로 차원 축소
    pca = PCA(n_components=2)
    components = pca.fit_transform(X_scaled)

    # 데이터프레임으로 변환
    pca_df = pd.DataFrame(data=components, columns=['PC1', 'PC2'])
    pca_df['Type'] = y.values

    # 유형의 앞글자(M/N: 수면패턴)만 따서 모양으로 구분해보기
    pca_df['Sleep_Type'] = pca_df['Type'].apply(lambda x: x[0])

    plt.figure(figsize=(12, 8))
    sns.scatterplot(
        x='PC1', y='PC2',
        hue='Type',           # 색깔은 16개 유형 전체
        style='Sleep_Type',   # 모양은 아침형/저녁형 구분
        data=pca_df,
        palette='tab20',      # 다양한 색상 팔레트
        s=100,                # 점 크기
        alpha=0.8             # 투명도
    )
    plt.title('16개 유형 데이터 분포 (PCA 차원축소)', fontsize=15)
    plt.legend(bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0.)
    plt.tight_layout()
    plt.show()

    print("\n--- [산점도 해석 팁] ---")
    print("1. 점들이 하나의 큰 덩어리로 뭉쳐있지 않고, 끼리끼리 뭉쳐있어야 합니다.")
    print("2. 16개 색깔이 완전히 따로 떨어질 필요는 없지만, 최소한 4~5개의 큰 그룹은 보여야 합니다.")

# 실행
visualize_data_quality(df_16types)

import pandas as pd

def show_data_summary(df):
    # 'type_label'을 기준으로 그룹을 묶고 평균을 계산합니다.
    summary_df = df.groupby('type_label').mean().round(2)

    # 보기 좋게 인원수(count) 컬럼도 추가합니다.
    summary_df['count'] = df['type_label'].value_counts()

    # 분석하기 편하게 주요 컬럼만 뽑아서 봅니다 (원하면 전체를 봐도 됩니다)
    key_columns = [
        'sleep_habit', 'clean_immediate', 'phone_noise', 'social_willingness', # 각 축의 대표 문항
        'clean_cycle', # 0~3 값을 가지는 특이 문항
        'count'        # 인원 수
    ]

    print("\n📊 [16개 유형별 평균 데이터 점검표]")
    print("-" * 60)
    # 전체 컬럼을 보고 싶으면 key_columns 대신 summary_df 를 출력하세요.
    print(summary_df[key_columns])
    print("-" * 60)

    return summary_df

# 실행
summary_table = show_data_summary(df_16types)