# -*- coding: utf-8 -*-
"""[2025-2 해커톤]유저 매칭 모델_시각화.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mTKEqnL9Fd1M6arSm0uEEDRu3Ub3zL31
"""

# 1. 나눔 폰트 설치
!sudo apt-get update -y
!sudo apt-get install -y fonts-nanum

# 2. 폰트 캐시 갱신
!sudo fc-cache -fv

# 3. matplotlib 캐시 삭제 (중요)
!rm ~/.cache/matplotlib -rf

print("폰트 설치가 완료되었습니다. 상단 메뉴의 [런타임] -> [세션 다시 시작]을 클릭하세요!")

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns
import pandas as pd
import numpy as np

# 1. 폰트 경로 설정 (나눔바른고딕)
plt.rc('font', family='NanumBarunGothic')

# 2. 마이너스 기호 깨짐 방지
plt.rc('axes', unicode_minus=False)

# 3. 폰트가 잘 적용되었는지 테스트 그래프 그려보기
plt.figure(figsize=(5, 5))
plt.title("한글 폰트 테스트")
plt.plot([1, 2, 3], [1, 4, 9])
plt.text(2, 4, "한글 잘 나옵니다!", ha='center')
plt.show()

# --- 테스트가 성공하면 아까 그 전체 코드를 다시 실행하세요 ---

W_P = 4  # Personality (성격/예민)
W_S = 3  # Sleep (수면)
W_C = 2  # Cleanliness (청결)

# 각 항목별 가중치 매핑
weight_A = {
    # [수면 패턴]
    "sleep_habit": W_S,       # 취침 시간
    "wake_up": W_S,           # 기상 시간
    "activity_time": W_S,     # 주 활동 시간
    "out_return": W_S,        # 외출/복귀 예민도

    # [청결도]
    "clean_immediate": W_C,   # 머리카락 치우기
    "desk_status": W_C,       # 책상 정리
    "clean_cycle": W_C,       # 청소 주기 (0~3)
    "other_seat_tol": W_C,    # 타인 자리 더러움 허용도

    # [성격/예민함/생활양식]
    "phone_noise": W_P,       # 통화 소음
    "light_sensitivity": W_P, # 불 켜고 잠
    "key_mouse_noise": W_P,   # 타건 소음
    "alarm_habit": W_P,       # 알람 습관
    "social_willingness": W_P,# 친목 도모
    "friend_invite": W_P,     # 친구 초대
    "dorm_stay": W_P,         # 기숙사 체류 시간
    "space_privacy": W_P      # 영역 침범
}

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
import platform
from sklearn.manifold import TSNE # 상단에 추가
from mpl_toolkits.mplot3d import Axes3D

# ---------------------------------------------------------
# 0. 시각화 폰트 설정 (OS별 자동화)
# ---------------------------------------------------------
system_name = platform.system()
if system_name == 'Darwin': # Mac
    plt.rc('font', family='AppleGothic')
elif system_name == 'Windows': # Windows
    plt.rc('font', family='Malgun Gothic')
else: # Linux (Colab 등)
    # Colab에서는 나눔글꼴 설치가 필요할 수 있음
    plt.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus'] = False

# ---------------------------------------------------------
# 1. 매칭 엔진 클래스 (수정됨)
# ---------------------------------------------------------
class DormMatchAI_Advanced:
    def __init__(self, data_path):
        self.data_path = data_path
        self.users_df = None
        self.weighted_features = None

        # [수정 1] 가중치 딕셔너리 직접 정의 (성격4 : 수면3 : 청결1)
        self.weights = weight_A

        # [수정 2] 결과 해석용 텍스트 매핑 보완
        self.text_map = {
            "sleep_habit": {0: "12시전 취침", 1: "새벽 취침"},
            "wake_up": {0: "늦잠/오후", 1: "아침 기상"},
            "activity_time": {0: "낮 활동", 1: "밤 활동"},
            "clean_cycle": {0: "매일", 1: "3일마다", 2: "1주마다", 3: "1달마다"},
            "phone_noise": {0: "상관없음", 1: "나가서 통화"},
            "clean_immediate": {0: "나중에", 1: "바로바로"},
            "social_willingness": {0: "개인주의", 1: "친목선호"},
            "is_smoker": {True: "흡연", False: "비흡연"}
        }

        # 한글 항목명 매핑
        self.col_name_map = {
            "sleep_habit": "수면시간", "wake_up": "기상시간", "activity_time": "활동시간",
            "clean_cycle": "청소주기", "phone_noise": "통화소음", "space_privacy": "공간존중",
            "clean_immediate": "정리습관", "social_willingness": "사회성"
        }

    def load_and_preprocess(self):
        with open(self.data_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # [수정 3] 데이터 로딩 로직 간소화 (이미 Flat한 구조임)
        # 생성된 JSON은 중첩이 없으므로 바로 DataFrame으로 변환
        self.users_df = pd.DataFrame(data)

        # 가중치 계산을 위한 컬럼 리스트
        self.feature_cols = list(self.weights.keys())

        # 정규화 및 가중치 적용
        scaler = MinMaxScaler()
        # 데이터프레임에서 feature_cols만 뽑아서 정규화
        features_norm = scaler.fit_transform(self.users_df[self.feature_cols])
        self.weighted_features = pd.DataFrame(features_norm, columns=self.feature_cols)

        # 가중치 곱하기
        for col, weight in self.weights.items():
            self.weighted_features[col] *= weight

    def train_clustering(self, n_clusters=12):
        # K-Means 수행
        kmeans = KMeans(n_clusters=n_clusters, random_state=42)
        self.users_df['cluster_id'] = kmeans.fit_predict(self.weighted_features)
        print(f"✅ 클러스터링 완료: 전체 유저를 {n_clusters}개의 성향 그룹으로 분류했습니다.")

    def explain_match_detail(self, me_row, partner_row):
        """매칭된 이유 분석"""
        reasons = {"match": [], "conflict": []}

        for col in self.feature_cols:
            val_me = me_row[col]
            val_partner = partner_row[col]

            col_name_kr = self.col_name_map.get(col, col)

            # 값이 비슷하면 매칭 성공 (완전 일치가 아니더라도 차이가 적으면)
            if val_me == val_partner:
                  reasons["match"].append(col_name_kr)
            else:
                # 값이 다르면 갈등 요소
                my_val_txt = self.text_map.get(col, {}).get(val_me, str(val_me))
                pt_val_txt = self.text_map.get(col, {}).get(val_partner, str(val_partner))
                reasons["conflict"].append(f"{col_name_kr}(나:{my_val_txt} vs 쟤:{pt_val_txt})")

        return reasons

    def find_best_match(self, target_student_id, top_n=3):
        # [수정 4] user_id 대신 student_id 사용
        try:
            target_idx = self.users_df[self.users_df['student_id'] == target_student_id].index[0]
        except IndexError:
            print(f"❌ 에러: 학번 {target_student_id}를 찾을 수 없습니다.")
            return [], -1

        target_vec = self.weighted_features.iloc[target_idx].values.reshape(1, -1)
        target_gender = self.users_df.iloc[target_idx]['gender']
        target_cluster = self.users_df.iloc[target_idx]['cluster_id']

        # 후보군 필터링: 성별 일치 AND 같은 클러스터
        candidates = self.users_df[
            (self.users_df['student_id'] != target_student_id) &
            (self.users_df['gender'] == target_gender) &
            (self.users_df['cluster_id'] == target_cluster)
        ].copy()

        # 예외 처리: 같은 클러스터에 사람이 없으면 전체 확장
        if len(candidates) < top_n:
             print("⚠️ 같은 성향 그룹 내 후보 부족 -> 전체 그룹으로 확장 검색")
             candidates = self.users_df[
                (self.users_df['student_id'] != target_student_id) &
                (self.users_df['gender'] == target_gender)
            ].copy()

        # 코사인 유사도 계산
        candidate_vecs = self.weighted_features.loc[candidates.index]
        sims = cosine_similarity(target_vec, candidate_vecs)[0]
        candidates['match_score'] = sims * 100

        # Top N 선정
        top_matches = candidates.sort_values(by='match_score', ascending=False).head(top_n)

        results = []
        me_row = self.users_df.iloc[target_idx]

        for _, partner_row in top_matches.iterrows():
            explanation = self.explain_match_detail(me_row, partner_row)
            match_info = partner_row.to_dict()
            match_info['explanation'] = explanation
            results.append(match_info)

        return results, target_student_id

    def visualize1(self, target_student_id, top_matches):
        # 1. PCA 차원 축소 및 데이터프레임 생성
# [수정됨] 1. PCA 대신 t-SNE 사용
        # n_components=2: 2차원으로 축소
        # perplexity: 보통 30~50 사이를 씁니다. 데이터가 적다면(수백 개 이하) 5~10 정도로 낮춰보세요.
        # random_state: 실행할 때마다 모양이 바뀌지 않도록 고정
        tsne = TSNE(n_components=2, random_state=42, perplexity=30)
        tsne_points = tsne.fit_transform(self.weighted_features)

        viz_df = pd.DataFrame(tsne_points, columns=['x', 'y'])
        viz_df['cluster'] = self.users_df['cluster_id']

        # 2. Jittering (t-SNE는 그룹 간 거리가 멀어지므로 noise_level을 조금 줄여도 됩니다)
        noise_level = 0.5 # t-SNE 좌표값은 PCA보다 클 수 있어서 상황 봐서 조정 (보통 0.5~1.0 추천)
        viz_df['x'] = viz_df['x'] + np.random.normal(0, noise_level, size=len(viz_df))
        viz_df['y'] = viz_df['y'] + np.random.normal(0, noise_level, size=len(viz_df))

        # 3. [핵심 변경] 색상 구분 로직
        # 타겟 유저의 인덱스 및 클러스터 ID 찾기
        target_idx = self.users_df[self.users_df['student_id'] == target_student_id].index[0]
        target_cluster = self.users_df.iloc[target_idx]['cluster_id']

        # 'color_group' 컬럼 생성: 내 클러스터='Same Group', 나머지='Others'
        viz_df['color_group'] = viz_df['cluster'].apply(
            lambda x: '나와 같은 성향 그룹' if x == target_cluster else '다른 성향 그룹들'
        )

        # 시각화 시작
        plt.figure(figsize=(12, 8))

        # 4. 배경 산점도 그리기 (커스텀 팔레트 사용)
        sns.scatterplot(
            x='x', y='y',
            hue='color_group', # 클러스터 ID 대신 새로 만든 그룹으로 색상 구분
            data=viz_df,
            palette={'나와 같은 성향 그룹': '#2ca02c', '다른 성향 그룹들': '#d3d3d3'}, # 초록색 vs 회색
            alpha=0.7, s=80, legend='full'
        )

        # 5. 나(Me)와 추천 룸메이트 하이라이트 (기존과 동일, 좌표는 Jitter 적용된 값 사용)
        plt.scatter(viz_df.iloc[target_idx]['x'], viz_df.iloc[target_idx]['y'],
                    c='red', s=400, marker='*', label='나 (Me)', edgecolors='white', linewidth=2, zorder=10)

        for i, match in enumerate(top_matches):
            p_idx = self.users_df[self.users_df['student_id'] == match['student_id']].index[0]
            plt.scatter(viz_df.iloc[p_idx]['x'], viz_df.iloc[p_idx]['y'],
                        c='blue', s=200, marker='X', label=f'추천 {i+1}위', edgecolors='white', linewidth=1, zorder=10)

            # 화살표 그리기
            plt.arrow(viz_df.iloc[target_idx]['x'], viz_df.iloc[target_idx]['y'],
                      viz_df.iloc[p_idx]['x'] - viz_df.iloc[target_idx]['x'],
                      viz_df.iloc[p_idx]['y'] - viz_df.iloc[target_idx]['y'],
                      color='gray', alpha=0.5, linestyle='--', width=0.002, zorder=9)

        # 6. 그래프 꾸미기
        plt.title(f'AI 기숙사 매칭 시각화 (학번: {target_student_id})', fontsize=16)
        plt.xlabel('성향 PC1')
        plt.ylabel('성향 PC2')
        # 범례 순서 및 위치 조정
        handles, labels = plt.gca().get_legend_handles_labels()
        order = [0, 1, 2, 3, 4] # 범례 표시 순서 (그룹2개 + 나 + 추천3명)
        plt.legend([handles[idx] for idx in order],[labels[idx] for idx in order], loc='upper right')

        plt.grid(True, alpha=0.2)
        plt.show()

    def visualize2(self, target_student_id, top_matches):
              # 1. PCA 차원 축소 및 데이터프레임 생성
# [수정됨] 1. PCA 대신 t-SNE 사용
        # n_components=2: 2차원으로 축소
        # perplexity: 보통 30~50 사이를 씁니다. 데이터가 적다면(수백 개 이하) 5~10 정도로 낮춰보세요.
        # random_state: 실행할 때마다 모양이 바뀌지 않도록 고정
        tsne = TSNE(n_components=2, random_state=42, perplexity=30)
        tsne_points = tsne.fit_transform(self.weighted_features)

        viz_df = pd.DataFrame(tsne_points, columns=['x', 'y'])
        viz_df['cluster'] = self.users_df['cluster_id']

        # 2. Jittering (t-SNE는 그룹 간 거리가 멀어지므로 noise_level을 조금 줄여도 됩니다)
        noise_level = 0.5 # t-SNE 좌표값은 PCA보다 클 수 있어서 상황 봐서 조정 (보통 0.5~1.0 추천)
        viz_df['x'] = viz_df['x'] + np.random.normal(0, noise_level, size=len(viz_df))
        viz_df['y'] = viz_df['y'] + np.random.normal(0, noise_level, size=len(viz_df))

        # 3. [핵심 변경] 색상 구분 로직
        # 타겟 유저의 인덱스 및 클러스터 ID 찾기
        target_idx = self.users_df[self.users_df['student_id'] == target_student_id].index[0]
        target_cluster = self.users_df.iloc[target_idx]['cluster_id']

        # 'color_group' 컬럼 생성: 내 클러스터='Same Group', 나머지='Others'
        viz_df['color_group'] = viz_df['cluster'].apply(
            lambda x: '나와 같은 성향 그룹' if x == target_cluster else '다른 성향 그룹들'
        )
        plt.figure(figsize=(12, 8))

        # 4. [수정됨] 배경 산점도 그리기 (12개 그룹별 색상 적용)
        sns.scatterplot(
            x='x', y='y',
            hue='cluster',   # 'color_group' 대신 'cluster' 컬럼(0~11)을 바로 사용
            data=viz_df,
            palette='tab20', # 12개 이상 색상을 뚜렷하게 구분해주는 팔레트 ('tab20', 'Set3' 등 추천)
            alpha=0.6,       # 점들이 많으니 투명도를 약간 주어 겹침 확인
            s=80,
            legend='full'    # 범례 표시
        )

        # 5. 나(Me)와 추천 룸메이트 하이라이트 (기존 코드 유지)
        # (이 부분은 그대로 두시면, 12색 배경 위에서도 빨간 별과 파란 X가 잘 보입니다)
        plt.scatter(viz_df.iloc[target_idx]['x'], viz_df.iloc[target_idx]['y'],
                    c='red', s=400, marker='*', label='나 (Me)', edgecolors='white', linewidth=2, zorder=10)

        for i, match in enumerate(top_matches):
            p_idx = self.users_df[self.users_df['student_id'] == match['student_id']].index[0]
            plt.scatter(viz_df.iloc[p_idx]['x'], viz_df.iloc[p_idx]['y'],
                        c='blue', s=200, marker='X', label=f'추천 {i+1}위', edgecolors='white', linewidth=1, zorder=10)

            # 화살표 그리기 (기존 유지)
            plt.arrow(viz_df.iloc[target_idx]['x'], viz_df.iloc[target_idx]['y'],
                      viz_df.iloc[p_idx]['x'] - viz_df.iloc[target_idx]['x'],
                      viz_df.iloc[p_idx]['y'] - viz_df.iloc[target_idx]['y'],
                      color='gray', alpha=0.5, linestyle='--', width=0.002, zorder=9)

        # 6. 그래프 꾸미기
        plt.title(f'AI 기숙사 매칭 전체 그룹 분포 (학번: {target_student_id})', fontsize=16)

        # 범례 위치 조정 (그룹이 많아져서 그래프를 가릴 수 있으므로 밖으로 빼는 것을 추천)
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)

        plt.grid(True, alpha=0.2)
        plt.tight_layout() # 범례가 잘리지 않도록 레이아웃 자동 조정
        plt.show()
    def visualize3d(self, target_student_id, top_matches):
        # 1. t-SNE 3차원 축소
        # n_components=3으로 설정하여 x, y, z 좌표 생성
        tsne = TSNE(n_components=3, random_state=42, perplexity=30)
        tsne_points = tsne.fit_transform(self.weighted_features)

        viz_df = pd.DataFrame(tsne_points, columns=['x', 'y', 'z'])
        viz_df['cluster'] = self.users_df['cluster_id']

        # 2. 시각화 설정
        fig = plt.figure(figsize=(12, 10))
        ax = fig.add_subplot(111, projection='3d') # 3D 축 생성

        # 3. 12개 그룹별 산점도 그리기
        # 색상 팔레트 설정 (tab20)
        cmap = plt.get_cmap('tab20')

        # 각 클러스터별로 루프를 돌며 찍어야 범례(Legend)가 예쁘게 나옵니다.
        unique_clusters = sorted(viz_df['cluster'].unique())
        for cluster in unique_clusters:
            cluster_data = viz_df[viz_df['cluster'] == cluster]
            ax.scatter(cluster_data['x'], cluster_data['y'], cluster_data['z'],
                       label=f'Group {cluster}',
                       c=[cmap(cluster/20)], # tab20 컬러 매핑
                       s=40, alpha=0.4)

        # 4. 나(Me)와 추천 룸메이트 하이라이트
        target_idx = self.users_df[self.users_df['student_id'] == target_student_id].index[0]

        # 나 (빨간 별)
        me_x = viz_df.iloc[target_idx]['x']
        me_y = viz_df.iloc[target_idx]['y']
        me_z = viz_df.iloc[target_idx]['z']

        ax.scatter(me_x, me_y, me_z,
                   c='red', s=300, marker='*', label='나 (Me)',
                   edgecolors='white', linewidth=1.5, zorder=10)

        # 추천 룸메이트 (파란 X) 및 연결선
        for i, match in enumerate(top_matches):
            p_idx = self.users_df[self.users_df['student_id'] == match['student_id']].index[0]
            p_x = viz_df.iloc[p_idx]['x']
            p_y = viz_df.iloc[p_idx]['y']
            p_z = viz_df.iloc[p_idx]['z']

            ax.scatter(p_x, p_y, p_z,
                       c='blue', s=150, marker='X', label=f'추천 {i+1}위',
                       edgecolors='white', linewidth=1, zorder=10)

            # 3D 연결선 그리기
            ax.plot([me_x, p_x], [me_y, p_y], [me_z, p_z],
                    color='gray', alpha=0.5, linestyle='--', linewidth=1)

        # 5. 그래프 꾸미기
        ax.set_title(f'AI 기숙사 매칭 3D 분포 (학번: {target_student_id})', fontsize=16)
        ax.set_xlabel('t-SNE X')
        ax.set_ylabel('t-SNE Y')
        ax.set_zlabel('t-SNE Z')

        # 초기 뷰 각도 설정 (elev=위아래 각도, azim=좌우 회전 각도)
        # 이 각도를 조절해서 가장 잘 보이는 뷰를 찾아야 합니다.
        ax.view_init(elev=30, azim=45)

        # 범례를 그래프 밖으로
        plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
        plt.tight_layout()
        plt.show()

# ---------------------------------------------------------
# 2. 실행부
# ---------------------------------------------------------
# 1. 엔진 초기화 (파일 경로는 실제 환경에 맞게 수정하세요)
# 예: 'dormitory_users.json' 이 같은 폴더에 있어야 합니다.
file_path = 'dormitory_users.json'
engine = DormMatchAI_Advanced(file_path)
engine.load_and_preprocess()
engine.train_clustering()

# 2. 테스트할 랜덤 유저 선정
import random
random_idx = random.randint(0, len(engine.users_df) - 1)
test_student_id = engine.users_df.iloc[random_idx]['student_id']

# 3. 매칭 실행
matches, my_id = engine.find_best_match(test_student_id)

# 4. 결과 출력
print(f"\n📢 [매칭 결과 리포트] 신청자 학번: {my_id}")
print("="*65)
for i, m in enumerate(matches):
    # [수정 5] 키 이름 변경 (me_smoke -> is_smoker)
    smoke_txt = "흡연" if m['is_smoker'] else "비흡연"
    drink_txt = "음주" if m['is_drinker'] else "비음주"

    print(f"🥇 추천 {i+1}위 (학번: {m['student_id']}) - 일치율: {m['match_score']:.1f}%")
    print(f"   학과: {m['major']} ({m['age']}세) | {smoke_txt} / {drink_txt}")

    expl = m['explanation']
    print(f"   👍 [일치 항목]: {len(expl['match'])}개 (수면, 청결 등 주요 성향 일치)")

    if expl['conflict']:
        # 너무 많으면 3개만 출력
        conflicts = expl['conflict'][:3]
        print(f"   ⚠️ [조율 필요]: {', '.join(conflicts)} ... 외 {len(expl['conflict'])-3}건")
    else:
        print(f"   ✨ [Perfect]: 갈등 요소가 하나도 없습니다!")
    print("-" * 65)

# 5. 시각화
engine.visualize1(test_student_id, matches)
engine.visualize2(test_student_id, matches)

engine.visualize3d(test_student_id, matches)

def analyze_cluster_personas_advanced(engine):
    # 1. 분석할 컬럼 (엔진에 설정된 가중치 키값들을 자동으로 가져오기)
    # 직접 리스트를 적는 것보다, 엔진이 사용한 컬럼을 그대로 쓰는 게 안전합니다.
    valid_cols = engine.feature_cols

    # 클러스터별 평균 계산 (사람이 보기엔 원본 데이터 평균이 이해하기 좋으므로 users_df 사용 유지)
    cluster_means = engine.users_df.groupby('cluster_id')[valid_cols].mean()

    print("\n📊 [AI 기숙사 유형 상세 분석 리포트]")
    print("=" * 70)

    for cluster_id in cluster_means.index:
        row = cluster_means.loc[cluster_id]

        # --- 1. 명사 결정 (수면 패턴) ---
        noun = "일반러"
        if row['sleep_habit'] > 0.6: noun = "올빼미"
        elif row['sleep_habit'] < 0.4: noun = "얼리버드"

        # --- 2. 형용사 결정 (리스트에 담기) ---
        adjectives = []

        # 청소 (값이 낮을수록 자주 함)
        if row['clean_cycle'] < 1.0: adjectives.append("결벽증")
        elif row['clean_cycle'] < 1.8: adjectives.append("깔끔한")
        elif row['clean_cycle'] > 2.2: adjectives.append("털털한")

        # 소음
        if row['phone_noise'] > 0.6: adjectives.append("예민보스")
        elif row['phone_noise'] < 0.4: adjectives.append("무던한")

        # [수정] 리스트를 예쁜 문자열로 변환 (예: ['깔끔', '조용'] -> "깔끔 조용")
        adj_str = " ".join(adjectives)
        final_name = f"{adj_str} {noun} 유형" if adj_str else f"{noun} 유형"

        # 비율 계산
        ratio = len(engine.users_df[engine.users_df['cluster_id'] == cluster_id]) / len(engine.users_df) * 100

        print(f"🏷️  [Cluster {cluster_id}]: \"{final_name}\" (비율: {ratio:.1f}%)")
        print("-" * 40)

        # 주요 수치 출력
        for col in valid_cols:
            val = row[col]
            # 수치가 0/1 범주형이면 해석을 돕기 위해 출력
            print(f"    • {col:<20} : {val:.2f}")

        print("=" * 70)

# 실행
analyze_cluster_personas_advanced(engine)


from sklearn.ensemble import RandomForestClassifier
import pandas as pd

def analyze_feature_impact(engine):
    # 1. X 데이터 설정 [중요 수정]
    # K-Means가 실제로 '무엇'을 보고 나눴는지 알기 위해 '가중치가 적용된 데이터'를 사용해야 합니다.
    X = engine.weighted_features
    y = engine.users_df['cluster_id']

    # 2. 랜덤 포레스트로 역추적
    clf = RandomForestClassifier(n_estimators=100, random_state=42)
    clf.fit(X, y)

    # 3. 중요도 추출
    importances = pd.Series(clf.feature_importances_, index=X.columns)
    importances = importances.sort_values(ascending=False)

    # 4. 결과 출력
    print("\n📊 [클러스터링 영향력 분석] AI가 무엇을 보고 나눴는가? (가중치 포함)")
    print("=" * 60)
    for feature, score in importances.items():
        if score > 0.30:
            status = "✅ 결정적 (범인)"
        elif score > 0.15:
            status = "⚠️ 영향 있음"
        elif score > 0.05:
            status = "🔍 미미함"
        else:
            status = "❌ 무시됨"

        print(f" • {feature:<20} : {score:.4f}  [{status}]")
    print("=" * 60)

# 실행
analyze_feature_impact(engine)

from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

def find_optimal_k(engine, max_k=20):
    inertias = []
    silhouettes = []
    K_range = range(2, max_k + 1) # 2개부터 20개까지 테스트

    print(f"📊 클러스터 개수(K)를 2부터 {max_k}까지 테스트 중...", end="")

    for k in K_range:
        # 모델 생성 및 학습
        kmeans = KMeans(n_clusters=k, random_state=42)
        kmeans.fit(engine.weighted_features)

        # 1. 관성(Inertia): 낮을수록 좋음 (군집 내 응집도)
        inertias.append(kmeans.inertia_)

        # 2. 실루엣 점수(Silhouette): 1에 가까울수록 좋음 (군집 간 분리도)
        score = silhouette_score(engine.weighted_features, kmeans.labels_)
        silhouettes.append(score)
        print(".", end="") # 진행상황 표시

    print(" 완료!")

    # --- 시각화 ---
    fig, ax1 = plt.subplots(figsize=(14, 6))

    # 왼쪽 축: 엘보우 기법 (Inertia)
    color = 'tab:blue'
    ax1.set_xlabel('클러스터 개수 (K)', fontsize=12)
    ax1.set_ylabel('Inertia (낮을수록 좋음)', color=color, fontsize=12)
    ax1.plot(K_range, inertias, 'o--', color=color, label='Inertia')
    ax1.tick_params(axis='y', labelcolor=color)
    ax1.set_xticks(K_range)
    ax1.grid(True, alpha=0.3)

    # 오른쪽 축: 실루엣 점수
    ax2 = ax1.twinx()
    color = 'tab:red'
    ax2.set_ylabel('실루엣 점수 (높을수록 좋음)', color=color, fontsize=12)
    ax2.plot(K_range, silhouettes, 's-', color=color, label='Silhouette')
    ax2.tick_params(axis='y', labelcolor=color)

    # 제목 및 그래프 표시
    plt.title('적정 클러스터 개수(K) 찾기: 엘보우 & 실루엣 분석', fontsize=16)
    fig.tight_layout()
    plt.show()

# 실행
find_optimal_k(engine, max_k=20)